apiVersion: apps/v1
kind: Deployment
metadata:
  name: madt4bc-databases
  namespace: dynabic
  labels:
    app: madt4bc-databases
spec:
  replicas: 1
  selector:
    matchLabels:
      app: madt4bc-databases
  template:
    metadata:
      labels:
        app: madt4bc-databases
    spec:
      containers:
      - name: sindit-neo4j-kg
        image: neo4j:4.4-community
        ports: ## Ports to map
        - containerPort: 7474
          name: http
        - containerPort: 7687
          name: bolt
        - containerPort: 7473
          name: https
        env: ## Env variables to pass
        - name: NEO4J_dbms_security_procedures_unrestricted
          value: "algo.*"
        - name: NEO4J_dbms_directories_plugins
          value: "plugins"
        - name: NEO4J_AUTH
          value: "neo4j/sindit-neo4j"
        - name: NEO4JLABS_PLUGINS
          value: '["apoc", "graph-algorithms"]'
        - name: NEO4J_dbms_security_procedures_unrestricted
          value: "apoc.*,algo.*,gds.*"
        - name: NEO4J_dbms_security_procedures_whitelist
          value: "apoc.*,algo.*,gds.*"
        - name: NEO4J_dbms.security.procedures.allowlist
          value: "gds.*"
        - name: NEO4J_apoc_import_file_enabled
          value: "true"
        - name: NEO4J_dbms_shell_enabled
          value: "true"
        volumeMounts: ## Volumes to mount
        - name: madt4bc-db
          mountPath: "/var/lib/neo4j/plugins"
          subPath: "neo4j-plugins"
        - name: madt4bc-db
          mountPath: "/var/lib/neo4j/data"
          subPath: "neo4j-data"
      - name: sindit-influx-db
        image: neo4j:4.4-community
        ports: ## Ports to map
        - containerPort: 8086
          name: http
        env:
        - name: DOCKER_INFLUXDB_INIT_MODE
          value: setup
        - name: DOCKER_INFLUXDB_INIT_USERNAME
          value: sindit_influxdb
        - name: DOCKER_INFLUXDB_INIT_PASSWORD
          value: sindit_influxdb
        - name: DOCKER_INFLUXDB_INIT_ORG
          value: sindit
        - name: DOCKER_INFLUXDB_INIT_BUCKET
          value: sindit
        - name: DOCKER_INFLUXDB_INIT_ADMIN_TOKEN
          value: sindit_influxdb_admin_token
        volumeMounts:
        - name: madt4bc-db
          mountPath: /var/lib/influxdb2
          subPath: "influx-db"
        - name: madt4bc-db
          mountPath: /etc/influxdb2
          subPath: "influx-config"
      - name: sindit-minio-s3
        image: minio/minio
        ports: ## Ports to map
        - containerPort: 9000
          name: http
        - containerPort: 9099
          name: tcp
        env:
        - name: MINIO_ACCESS_KEY
          value: sindit_minio_access_key
        - name: MINIO_SECRET_KEY
          value: sindit_minio_secret_key
        - name: MINIO_ROOT_USER
          value: sindit_minio
        - name: MINIO_ROOT_PASSWORD
          value: sindit_minio
        command: ["/bin/bash", "-c"]
        args: ['minio server /data --address 0.0.0.0:9000 --console-address :9099']
        volumeMounts:
        - name: madt4bc-db
          mountPath: data
          subPath: "minio-db"

      volumes:
      - name: madt4bc-db
        persistentVolumeClaim:
          claimName: madt4bc-db-pvc
