FROM python:3.10-slim

# Create and set the working directory
RUN mkdir /opt/connection
WORKDIR /opt/connection

# Copy all files to the working directory in the container
COPY . .

# Convert line endings for run.sh and all .py files to Unix format
RUN sed -i 's/\r$//' run_services.sh && \
    find . -name "*.py" -exec sed -i 's/\r$//' {} +

# Install Python dependencies from requirements.txt
RUN pip3 install -r requirements.txt

# Expose the necessary ports
EXPOSE 5002
EXPOSE 5003

# Give execute permission to run.sh
RUN chmod +x run_services.sh

# Specify the command to run when the container starts
CMD ["bash", "run_services.sh"]
