FROM python:3.10-slim

# Create and set the working directory
RUN mkdir /opt/connection
WORKDIR /opt/connection

COPY ./requirements.txt ./requirements.txt

# Install Python dependencies from requirements.txt
RUN pip3 install -r requirements.txt

# Copy all files to the working directory in the container
COPY . .

# Convert line endings for run.sh and all .py files to Unix format
RUN sed -i 's/\r$//' run_db.sh && \
    find . -name "*.py" -exec sed -i 's/\r$//' {} +

# Expose the necessary ports
EXPOSE 4999
EXPOSE 5000
EXPOSE 5001

# Give execute permission to run.sh
RUN chmod +x run_db.sh

# Specify the command to run when the container starts
CMD ["bash", "run_db.sh"]
