FROM python:3.9

# Create and set the working directory
WORKDIR /usr/api

COPY ./requirements.txt ./requirements.txt

# Install Python dependencies from requirements.txt
RUN pip3 install -r requirements.txt

# Copy all files to the working directory in the container
COPY . .

# Convert line endings for run.sh and all .py files to Unix format
RUN sed -i 's/\r$//' run_api.sh && \
    find . -name "*.py" -exec sed -i 's/\r$//' {} +



# Expose the necessary ports
EXPOSE 4999
EXPOSE 5000
EXPOSE 5001
EXPOSE 5002
EXPOSE 5003
EXPOSE 5004

# Give execute permission to run.sh
RUN chmod +x run_api.sh

CMD ["bash", "run_api.sh"]
